import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { decrement, increment } from '../store/countSlice'
import { getPosts, getUsers, reset } from '../store/postsSlice'
import { asyncIncrement } from '../store/slices/count/asyncAction'
import { AppDispatch, TStore } from '../store/types'
import styles from '../styles/Home.module.css'

const Home = () => {
  const dispatch = useDispatch<AppDispatch>()
  const countStore = useSelector((store: TStore) => store.count)
  const postsStore = useSelector((store: TStore) => store.posts)

  console.log(countStore)

  const renderCards = () =>
    postsStore.posts.map((card) => (
      <div className={styles.card} key={card.id}>
        <h2>{card.title}</h2>
        <p>{card.body}</p>
      </div>
    ))

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Redux Toolkit</h1>

        <div className={styles.cardsWrapper}>
          {countStore.count}
          <button onClick={() => dispatch(reset())}>Reset</button>

          <button onClick={() => dispatch(increment(5))}>Increment</button>
          <button onClick={() => dispatch(asyncIncrement(5))}>Async Increment</button>
          <button onClick={() => dispatch(decrement(1))}>Decrement</button>
          <button onClick={() => dispatch(getPosts())}>Get Posts</button>
          <button onClick={() => dispatch(getUsers())}>Get Users</button>

          {renderCards()}
        </div>
      </main>
    </div>
  )
}

export default Home
